[package]
name = "ic-repl"
version = "0.1.0"
authors = ["DFINITY Team"]
edition = "2018"

[build-dependencies]
lalrpop = "0.19"

[dependencies]
candid = { git = "https://github.com/dfinity/candid.git", branch = "fix-beta", features = ["random"] }
rustyline = "8.0"
rustyline-derive = "0.4"
ansi_term = "0.12"
codespan-reporting = "0.11"
pretty = "0.10.0"
ic-agent = { git = "https://github.com/dfinity/agent-rs.git", branch = "yan/test" }
tokio = { version = "1.5.0", features = ["full"] }
delay = "0.3.1"
anyhow = "1.0"
rand = "0.8"
logos = "0.12"
lalrpop-util = "0.19"
clap = "2.33"
structopt = "0.3.16"
ring = "0.16"

[patch.crates-io]
ic-types = { git = "https://github.com/dfinity/agent-rs.git", branch = "yan/test" }

