[package]
name = "ic-repl"
version = "0.1.0"
authors = ["DFINITY Team"]
edition = "2018"

[build-dependencies]
lalrpop = "0.19"

[dependencies]
candid = { git = "https://github.com/dfinity/candid.git", branch = "master", features = ["random"] }
rustyline = "8.2"
rustyline-derive = "0.4"
ansi_term = "0.12"
pretty_assertions = "0.7"
terminal_size = "0.1"
codespan-reporting = "0.11"
pretty = "0.10.0"
pem = "0.8"
shellexpand = "2.1"
ic-agent = "0.8.0"
tokio = { version = "1.6.0", features = ["full"] }
garcon = "0.2.3"
anyhow = "1.0"
rand = "0.8"
logos = "0.12"
lalrpop-util = "0.19"
clap = "2.33"
structopt = "0.3.16"
ring = "0.16"
serde = "1.0"
serde_json = "1.0"
hex = { version = "0.4", features = ["serde"] }
openssl = "0.10"
crc32fast = "1.2"
qrcode = { version = "0.12", default-features = false }
libflate = "1.1"
base64 = "0.13"

[features]
static-ssl = ["openssl/vendored"]
