[package]
name = "ic-repl"
version = "0.1.0"
authors = ["DFINITY Team"]
edition = "2018"

[build-dependencies]
lalrpop = "0.19"

[dependencies]
candid = { git = "https://github.com/dfinity/candid.git", branch = "beta", features = ["random"] }
rustyline = "8.0"
rustyline-derive = "0.4"
ansi_term = "0.12"
pretty_assertions = "0.7"
terminal_size = "0.1"
codespan-reporting = "0.11"
pretty = "0.10.0"
pem = "0.8"
shellexpand = "2.1"
ic-agent = "0.4.1"
tokio = { version = "1.5.0", features = ["full"] }
delay = "0.3.1"
anyhow = "1.0"
rand = "0.8"
logos = "0.12"
lalrpop-util = "0.19"
clap = "2.33"
structopt = "0.3.16"
ring = "0.16"
serde = "1.0"
